spring:
  application:
    name: movieflix

  datasource:
    url: jdbc:postgresql://localhost:5432/movieflix
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

  flyway:
    enabled: true

movieFlix:
  security:
    secret: "lO5qTcImQ0DvxXyo8InsytNmjjSjz4Ao+asPFRdcfEE="

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger/index.html